version: '3.8'
services:
  app:
    build: .
    container_name: url-shortener
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_URL=postgres://youruser:yourpassword@postgres:5432/url_shortener?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
